### ISSUE TITLE
panic: runtime error: index out of range in ui_writer.go

### ISSUE THREAD

**Issue by jakubzytka** [mitchellh/cli#26]
Running consul v0.6 I encountered a panic:

```
panic: runtime error: index out of range
 

goroutine 1 [running]:
github.com/mitchellh/cli.(*UiWriter).Write(0xc82015d640, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /golang/workspace/src/github.com/mitchellh/cli/ui_writer.go:12 +0xf0
github.com/hashicorp/consul/command/agent.(*GatedWriter).Write(0xc8200ea5f0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /golang/workspace/src/github.com/hashicorp/consul/command/agent/gated_writer.go:36 +0x112
github.com/hashicorp/consul/command/agent.(*GatedWriter).Flush(0xc8200ea5f0)
        /golang/workspace/src/github.com/hashicorp/consul/command/agent/gated_writer.go:26 +0x107
github.com/hashicorp/consul/command/agent.(*Command).Run(0xc82013e000, 0xc82000a140, 0x10, 0x10, 0x0)
        /golang/workspace/src/github.com/hashicorp/consul/command/agent/command.go:715 +0x23ba
github.com/mitchellh/cli.(*CLI).Run(0xc82013c000, 0xc82013c000, 0x0, 0x0)
        /golang/workspace/src/github.com/mitchellh/cli/cli.go:112 +0x655
main.realMain(0xc820000180)
        /golang/workspace/src/github.com/hashicorp/consul/main.go:40 +0x214
main.main()
        /golang/workspace/src/github.com/hashicorp/consul/main.go:12 +0x18

.....
     (lots of tracebacks)
.....
```

Indeed, UiWriter::Write makes an optimistic assumption about p length in:

<pre>
func (w *UiWriter) Write(p []byte) (n int, err error) {
	n = len(p)
	<b>if p[n-1] == '\n'</b> {
		p = p[:n-1]
	}

	w.Ui.Info(string(p))
	return n, nil
}
</pre>

I do not have a core.

**Comment by mitchellh** [comment]
Good catch. Fixed with test.
