### ISSUE TITLE
BasicUi.Ask functionality throws a panic

### ISSUE THREAD

**Issue by thirumarant** [mitchellh/cli#29]
```golang
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0xec913]

goroutine 8 [running]:
panic(0x371ac0, 0xc8200120c0)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
bufio.(*Reader).fill(0xc82002cee8)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e3
bufio.(*Reader).ReadSlice(0xc82003fed8, 0x1380a, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:328 +0x21a
bufio.(*Reader).ReadBytes(0xc82003fed8, 0x2ddb0a, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:406 +0xa9
bufio.(*Reader).ReadString(0xc82003fed8, 0xc82002ce0a, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:446 +0x4d
github.com/mitchellh/cli.(*BasicUi).ask.func1(0xc820068500, 0xc82000ef00, 0xc820068540, 0xc8200685a0)
	/Users/thirumarant/workspace/src/github.com/mitchellh/cli/ui.go:85 +0x27d
created by github.com/mitchellh/cli.(*BasicUi).ask
	/Users/thirumarant/workspace/src/github.com/mitchellh/cli/ui.go:93 +0x345
```

Using the Ask function keeps throwing a panic

**Comment by acowan** [comment]
Thirumarant, do you have some sample code that replicates this, or does it always occur regardless of the input?

**Comment by thirumarant** [comment]
My code
```
ui := &cli.BasicUi{Writer: os.Stdout}

	meta := command.Meta {
		Ui: ui,
	}

	Commands = map[string]cli.CommandFactory{

		"apply": func() (cli.Command, error) {
			return &command.ApplyCommand {
				Ui: ui,
			}, nil
		},

		"create": func() (cli.Command, error) {
			return &command.CreateCommand {
				Meta: meta,
				Ui: ui,
			}, nil
		},
```
I worked out that I wasn't passing in a reader. Correcting the code to this worked as expected

```
ui := &cli.BasicUi{Writer: os.Stdout, Reader: os.Stdin}
```
The thing that threw me off was, using AskSecret worked without passing the reader but as soon as I started using Ask the panic started
